-- return {
-- 	"yetone/avante.nvim",
-- 	enabled = true,
-- 	event = "VeryLazy",
-- 	build = "make",
-- 	opts = {
-- 		-- add any opts here
-- 	},
-- 	dependencies = {
-- 		"nvim-tree/nvim-web-devicons",
-- 		"stevearc/dressing.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		--- The below is optional, make sure to setup it properly if you have lazy=true
-- 		{
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 				---@alias Provider "openai" | "claude" | "azure"  | "copilot" | [string]
-- 				provider = "claude",
-- 				claude = {
-- 					endpoint = "https://api.anthropic.com",
-- 					model = "claude-3-5-sonnet-20240620",
-- 					temperature = 0,
-- 					max_tokens = 4096,
-- 				},
-- 				mappings = {
-- 					ask = "<leader>aba",
-- 					edit = "<leader>abe",
-- 					refresh = "<leader>abr",
-- 					--- @class AvanteConflictMappings
-- 					diff = {
-- 						ours = "co",
-- 						theirs = "ct",
-- 						none = "c0",
-- 						both = "cb",
-- 						next = "]x",
-- 						prev = "[x",
-- 					},
-- 					jump = {
-- 						next = "]]",
-- 						prev = "[[",
-- 					},
-- 					submit = {
-- 						normal = "<CR>",
-- 						insert = "<C-s>",
-- 					},
-- 					toggle = {
-- 						debug = "<leader>abd",
-- 						hint = "<leader>abh",
-- 					},
-- 				},
-- 				hints = { enabled = true },
-- 				windows = {
-- 					wrap = true, -- similar to vim.o.wrap
-- 					width = 20, -- default % based on available width
-- 					sidebar_header = {
-- 						align = "center", -- left, center, right for title
-- 						rounded = true,
-- 					},
-- 				},
-- 				highlights = {
-- 					---@type AvanteConflictHighlights
-- 					diff = {
-- 						current = "DiffText",
-- 						incoming = "DiffAdd",
-- 					},
-- 				},
-- 				--- @class AvanteConflictUserConfig
-- 				diff = {
-- 					debug = false,
-- 					autojump = true,
-- 					---@type string | fun(): any
-- 					list_opener = "copen",
-- 				},
-- 			},
-- 		},
-- 		ft = { "markdown", "Avante" },
-- 	},
-- }
-- return {
-- 	"yetone/avante.nvim",
-- 	event = "VeryLazy",
-- 	lazy = false,
-- 	version = false, -- set this if you want to always pull the latest change
-- 	opts = {
-- 		-- add any opts here
-- 		provider = "copilot",
-- 		mappings = {
-- 			ask = "<leader>aya", -- ask
-- 			edit = "<leader>aye", -- edit
-- 			refresh = "<leader>ayr", -- refresh
-- 		},
-- 		windows = {
-- 			position = "right",
-- 			width = 35,
-- 			sidebar_header = {
-- 				enabled = true, -- true, false to enable/disable the header
-- 				align = "center", -- left, center, right for title
-- 				rounded = false,
-- 			},
-- 			ask = {
-- 				floating = true, -- Open the 'AvanteAsk' prompt in a floating window
-- 				start_insert = true, -- Start insert mode when opening the ask window
-- 				border = "rounded",
-- 				---@type "ours" | "theirs"
-- 				focus_on_apply = "theirs", -- which diff to focus after applying
-- 			},
-- 		},
-- 	},
-- 	-- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
-- 	build = "make",
-- 	-- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
-- 	dependencies = {
-- 		"nvim-treesitter/nvim-treesitter",
-- 		"stevearc/dressing.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		--- The below dependencies are optional,
-- 		"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
-- 		"zbirenbaum/copilot.lua", -- for providers='copilot'
-- 		{
-- 			-- support for image pasting
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				-- recommended settings
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = {
-- 						insert_mode = true,
-- 					},
-- 					-- required for Windows users
-- 					use_absolute_path = true,
-- 				},
-- 			},
-- 		},
-- 		{
-- 			-- Make sure to set this up properly if you have lazy=true
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 			},
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }

return {}
