return {
	"nvimdev/lspsaga.nvim",
	after = "nvim-lspconfig",
	event = "LspAttach",
	dependencies = {
		"nvim-treesitter/nvim-treesitter",
		"nvim-tree/nvim-web-devicons",
	},
	opts = {
		-- code_action = {
		-- 	keys = { quit = "<Esc>" },
		-- 	extensions = {
		-- 		extend_gitsigns = true,
		-- 	},
		-- },
		-- finder = {
		-- 	keys = {
		-- 		quit = "<Esc>",
		-- 		toggle_or_open = "<CR>",
		-- 	},
		-- },
		-- lightbulb = { enable = false },
		-- -- winbar = {
		-- -- 	enabled = false,
		-- -- },
		-- rename = {
		-- 	keys = { quit = "<Esc>" },
		-- },

		ui = {
			winbar_prefix = "",
			border = "rounded",
			devicon = true,
			foldericon = true,
			title = true,
			expand = "⊞",
			collapse = "⊟",
			code_action = "💡",
			lines = { "┗", "┣", "┃", "━", "┏" },
			kind = nil,
			button = { "", "" },
			imp_sign = "󰳛 ",
			use_nerd = true,
		},
		hover = {
			max_width = 0.9,
			max_height = 0.8,
			open_link = "gx",
			open_cmd = "!chrome",
		},
		diagnostic = {
			virtual_text = false,
			show_layout = "float",
			show_normal_height = 0,
			jump_num_shortcut = true,
			auto_preview = true,
			max_width = 0.8,
			max_height = 0.6,
			max_show_width = 0.9,
			max_show_height = 0.6,
			wrap_long_lines = false,
			extend_relatedInformation = true,
			diagnostic_only_current = false,
			keys = {
				exec_action = "o",
				quit = "q",
				toggle_or_jump = "<CR>",
				quit_in_show = { "q", "<ESC>" },
			},
		},
		code_action = {
			num_shortcut = true,
			show_server_name = false,
			extend_gitsigns = true,
			only_in_cursor = true,
			max_height = 0.3,
			cursorline = true,
			keys = {
				quit = "q",
				exec = "<CR>",
			},
		},
		lightbulb = {
			enable = false,
			sign = false,
			debounce = 10,
			sign_priority = 40,
			virtual_text = false,
			enable_in_insert = true,
			ignore = {
				clients = {},
				ft = {},
			},
		},
		scroll_preview = {
			scroll_down = "<Down>",
			scroll_up = "<Up>",
		},
		request_timeout = 2000,
		finder = {
			max_height = 0.5,
			left_width = 0.4,
			methods = {},
			default = "ref+imp+tyd",
			layout = "float",
			silent = false,
			filter = {},
			fname_sub = nil,
			sp_inexist = false,
			sp_global = false,
			ly_botright = false,
			number = vim.o.number,
			relativenumber = vim.o.relativenumber,
			keys = {
				shuttle = "[w",
				toggle_or_open = "o",
				vsplit = "s",
				split = "i",
				tabe = "t",
				tabnew = "r",
				quit = "q",
				close = "<C-c>k",
			},
		},
		definition = {
			width = 0.6,
			height = 0.5,
			save_pos = false,
			number = vim.o.number,
			relativenumber = vim.o.relativenumber,
			keys = {
				edit = "<C-o>",
				vsplit = "<C-v>",
				split = "<C-x>",
				tabe = "<C-t>",
				tabnew = "<C-c>n",
				quit = "q",
				close = "<ESC>",
			},
		},
		rename = {
			in_select = true,
			auto_save = false,
			project_max_width = 0.5,
			project_max_height = 0.5,
			keys = {
				quit = "<Esc>",
				exec = "<CR>",
				select = "x",
			},
		},
		outline = {
			win_position = "right",
			win_width = 30,
			auto_preview = true,
			detail = true,
			auto_close = true,
			close_after_jump = false,
			layout = "normal",
			max_height = 0.5,
			left_width = 0.3,
			keys = {
				toggle_or_jump = "o",
				quit = "q",
				jump = "e",
			},
		},
		callhierarchy = {
			layout = "float",
			left_width = 0.2,
			keys = {
				edit = "e",
				vsplit = "s",
				split = "i",
				tabe = "t",
				close = "<C-c>k",
				quit = "q",
				shuttle = "[w",
				toggle_or_req = "u",
			},
		},
		typehierarchy = {
			layout = "float",
			left_width = 0.2,
			keys = {
				edit = "e",
				vsplit = "s",
				split = "i",
				tabe = "t",
				close = "<C-c>k",
				quit = "q",
				shuttle = "[w",
				toggle_or_req = "u",
			},
		},
		implement = {
			enable = false,
			sign = true,
			lang = {},
			virtual_text = false,
			priority = 100,
		},
		beacon = {
			enable = true,
			frequency = 7,
		},
		floaterm = {
			height = 0.7,
			width = 0.7,
		},
	},
	keys = {
		{ "<Leader>ch", ":Lspsaga hover_doc<CR>", silent = true },
		-- { "<Leader>i", ":Lspsaga code_action<CR>", silent = true },
		{ "<Leader>cr", ":Lspsaga rename<CR>", silent = true, desc = "Rename" },
		{ "gr", ":Lspsaga finder<CR>", silent = true },
	},
}
