-- return {
-- {
-- 	"folke/tokyonight.nvim",
-- 	lazy = true,
-- 	opts = {
-- 		transparent = true,
-- 		styles = {
-- 			sidebars = "transparent",
-- 			floats = "transparent",
-- 		},
-- 		colorscheme = "night",
-- 		transparent_background = true,
-- 		background = "",
-- 	},
-- },
-- {
-- 	"folke/tokyonight.nvim",
-- 	lazy = true,
-- 	opts = { style = "moon" },
-- },
-- {
-- 	"folke/tokyonight.nvim",
-- 	opts = {
-- 		-- transparent = true,
-- 		styles = {
-- 			-- sidebars = "transparent",
-- 			-- floats = "transparent",
-- 		},
-- 	},
-- },
-- 	{
-- 		"LazyVim/LazyVim",
-- 		opts = {
-- 			colorscheme = "tokyonight",
-- 			-- transparent_background = true,
-- 			-- background = "",
-- 		},
-- 	},
-- }
return {}
-- return {
-- 	{
-- 		"LazyVim/LazyVim",
-- 		opts = { colorscheme = "tokyonight" },
-- 		dependencies = {
-- 			{
-- 				"folke/tokyonight.nvim",
-- 				opts = {
-- 					style = "moon",
-- 					lualine_bold = true, -- bold headers for each section header
-- 					-- day_brightness = 0.15, -- high contrast but colorful
--
-- 					-- jack up all saturation, default is too dull!
-- 					on_colors = function(colors)
-- 						local hsluv = require("tokyonight.hsluv")
-- 						local multiplier = 2.0
--
-- 						for k, v in pairs(colors) do
-- 							if type(v) == "string" and v ~= "NONE" then
-- 								local hsv = hsluv.hex_to_hsluv(v)
-- 								hsv[2] = hsv[2] * multiplier > 100 and 100 or hsv[2] * multiplier
-- 								colors[k] = hsluv.hsluv_to_hex(hsv)
-- 							elseif type(v) == "table" then
-- 								if vim.islist(v) then
-- 									for kk, vv in ipairs(v) do
-- 										if type(vv) == "string" and vv ~= "NONE" then
-- 											local hsv = hsluv.hex_to_hsluv(vv)
-- 											hsv[2] = hsv[2] * multiplier > 100 and 100 or hsv[2] * multiplier
-- 											colors[k][kk] = hsluv.hsluv_to_hex(hsv)
-- 										end
-- 									end
-- 								else
-- 									for kk, vv in pairs(v) do
-- 										if type(vv) == "string" and vv ~= "NONE" then
-- 											local hsv = hsluv.hex_to_hsluv(vv)
-- 											hsv[2] = hsv[2] * multiplier > 100 and 100 or hsv[2] * multiplier
-- 											colors[k][kk] = hsluv.hsluv_to_hex(hsv)
-- 										end
-- 									end
-- 								end
-- 							end
-- 						end
-- 					end,
-- 				},
-- 			},
-- 		},
-- 	},
-- }

-- return {
--   "catppuccin/nvim",
--   lazy = true,
--   name = "catppuccin",
--   opts = {
--     transparent = true,
--     styles = {
--       sidebars = "transparent",
--       floats = "transparent",
--     },
--     integrations = {
--       alpha = true,
--       cmp = true,
--       gitsigns = true,
--       illuminate = true,
--       indent_blankline = { enabled = true },
--       lsp_trouble = true,
--       mini = true,
--       native_lsp = {
--         enabled = true,
--         underlines = {
--           errors = { "undercurl" },
--           hints = { "undercurl" },
--           warnings = { "undercurl" },
--           information = { "undercurl" },
--         },
--       },
--       navic = { enabled = true },
--       neotest = true,
--       noice = true,
--       notify = true,
--       nvimtree = true,
--       semantic_tokens = true,
--       telescope = true,
--       treesitter = true,
--       which_key = true,
--     },
--   },
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "catppuccin",
--       transparent_background = true,
--       background = "",
--     },
--   },
-- }
